apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://dp-prometheus:9090/prometheus
    isDefault: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
